/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package autograph.ui;

public class AddEdgePanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNodePanel
     */
    public AddEdgePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        AddEdgePanel = new javax.swing.JPanel();
        AddEdgeTitleLabel = new javax.swing.JLabel();
        LabelSubtitleLabel = new javax.swing.JLabel();
        LabelTextLabel = new javax.swing.JLabel();
        LabelTextField = new javax.swing.JTextField();
        LabelFontLabel = new javax.swing.JLabel();
        LabelFontComboBox = new javax.swing.JComboBox();
        LabelColorLabel = new javax.swing.JLabel();
        LabelColorBtn = new javax.swing.JButton();
        EdgeSubtitleLabel = new javax.swing.JLabel();
        EdgeDesignLabel = new javax.swing.JLabel();
        EndShapeLabel = new javax.swing.JLabel();
        EdgeColorLabel = new javax.swing.JLabel();
        EdgeColorBtn = new javax.swing.JButton();
        EdgeDesignComboBox = new javax.swing.JComboBox();
        EndShapeComboBox = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        OkBtn = new javax.swing.JButton();
        SelectSourceNodeBtn = new javax.swing.JButton();
        SelectDestinationNodeBtn = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 32767));

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(200, 300));
        setPreferredSize(new java.awt.Dimension(200, 498));

        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        AddEdgePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        AddEdgePanel.setPreferredSize(new java.awt.Dimension(200, 459));

        AddEdgeTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddEdgeTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddEdgeTitleLabel.setText("Add Edge");

        LabelSubtitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelSubtitleLabel.setText("Label");

        LabelTextLabel.setText("Label Text");

        LabelFontLabel.setText("Label Font");

        LabelFontComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Times New Roman", "Ariel", "Some other font", "More fonts", "Wingdings" }));

        LabelColorLabel.setText("Label Color");

        LabelColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

        EdgeSubtitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EdgeSubtitleLabel.setText("Edge");

        EdgeDesignLabel.setText("Edge Design");

        EndShapeLabel.setText("End Shape");

        EdgeColorLabel.setText("Edge Color");

        EdgeColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

        EdgeDesignComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- - - -", "......", "===", " " }));
        EdgeDesignComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdgeDesignComboBoxActionPerformed(evt);
            }
        });

        EndShapeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A-A", "A-B", "A-C", "B-B", "B-C", "C-C" }));

        OkBtn.setText("Add Edge");
        OkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkBtnActionPerformed(evt);
            }
        });

        SelectSourceNodeBtn.setText("Select Source Node");
        SelectSourceNodeBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        SelectDestinationNodeBtn.setText("Select Destination Node");

        javax.swing.GroupLayout AddEdgePanelLayout = new javax.swing.GroupLayout(AddEdgePanel);
        AddEdgePanel.setLayout(AddEdgePanelLayout);
        AddEdgePanelLayout.setHorizontalGroup(
            AddEdgePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEdgePanelLayout.createSequentialGroup()
                .addGroup(AddEdgePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelSubtitleLabel)
                    .addComponent(EdgeSubtitleLabel))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(AddEdgePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddEdgePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddEdgeTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelTextField)
                    .addComponent(LabelFontComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddEdgePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(OkBtn))
                    .addGroup(AddEdgePanelLayout.createSequentialGroup()
                        .addGroup(AddEdgePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AddEdgePanelLayout.createSequentialGroup()
                                .addGroup(AddEdgePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelTextLabel)
                                    .addComponent(LabelFontLabel)
                                    .addComponent(EndShapeLabel)
                                    .addComponent(EdgeColorLabel))
                                .addGap(32, 32, 32)
                                .addGroup(AddEdgePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EdgeColorBtn)
                                    .addComponent(EndShapeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AddEdgePanelLayout.createSequentialGroup()
                                .addGroup(AddEdgePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EdgeDesignLabel)
                                    .addComponent(LabelColorLabel))
                                .addGap(25, 25, 25)
                                .addGroup(AddEdgePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EdgeDesignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelColorBtn)))
                            .addComponent(SelectDestinationNodeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SelectSourceNodeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AddEdgePanelLayout.setVerticalGroup(
            AddEdgePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEdgePanelLayout.createSequentialGroup()
                .addComponent(AddEdgeTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelSubtitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelFontLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelFontComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AddEdgePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelColorLabel)
                    .addComponent(LabelColorBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(EdgeSubtitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddEdgePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdgeDesignLabel)
                    .addComponent(EdgeDesignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddEdgePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EndShapeLabel)
                    .addComponent(EndShapeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddEdgePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdgeColorLabel)
                    .addComponent(EdgeColorBtn))
                .addGap(18, 18, 18)
                .addComponent(SelectSourceNodeBtn)
                .addGap(18, 18, 18)
                .addComponent(SelectDestinationNodeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OkBtn)
                .addContainerGap())
        );

        jScrollPane5.setViewportView(AddEdgePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EdgeDesignComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdgeDesignComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdgeDesignComboBoxActionPerformed

    private void OkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkBtnActionPerformed
        // TODO add your handling code here:
        String test = LabelTextLabel.getText();
        System.out.print(test);
    }//GEN-LAST:event_OkBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddEdgePanel;
    private javax.swing.JLabel AddEdgeTitleLabel;
    private javax.swing.JButton EdgeColorBtn;
    private javax.swing.JLabel EdgeColorLabel;
    private javax.swing.JComboBox EdgeDesignComboBox;
    private javax.swing.JLabel EdgeDesignLabel;
    private javax.swing.JLabel EdgeSubtitleLabel;
    private javax.swing.JComboBox EndShapeComboBox;
    private javax.swing.JLabel EndShapeLabel;
    private javax.swing.JButton LabelColorBtn;
    private javax.swing.JLabel LabelColorLabel;
    private javax.swing.JComboBox LabelFontComboBox;
    private javax.swing.JLabel LabelFontLabel;
    private javax.swing.JLabel LabelSubtitleLabel;
    private javax.swing.JTextField LabelTextField;
    private javax.swing.JLabel LabelTextLabel;
    private javax.swing.JButton OkBtn;
    private javax.swing.JButton SelectDestinationNodeBtn;
    private javax.swing.JButton SelectSourceNodeBtn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
