/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package autograph.ui;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.GraphicsEnvironment;

import javax.swing.*;

import autograph.Graph;
import autograph.GraphHelper;
import autograph.GraphPanel;
import autograph.Node;
import autograph.exception.CannotAddNodeException;

public class AddNodePanel extends JPanel {

	/**
	 * Creates new form AddNodePanel
	 */
	public AddNodePanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane5 = new JScrollPane();
		AddNodePanel = new JPanel();
		AddNodeTitleLabel = new JLabel();
		LabelSubtitleLabel = new JLabel();
		LabelTextLabel = new JLabel();
		LabelTextField = new JTextField();
		LabelFontLabel = new JLabel();
		LabelFontComboBox = new JComboBox();
		LabelColorLabel = new JLabel();
		LabelColorBtn = new JButton();
		NodeSubtitleLabel = new JLabel();
		NodeShapeLabel = new JLabel();
		BorderColorLabel = new JLabel();
		FillColorLabel = new JLabel();
		FillColorBtn = new JButton();
		NodeShapeComboBox = new JComboBox();
		BorderColorBtn = new JButton();
		jSeparator1 = new JSeparator();
		jButton1 = new JButton();
		filler1 = new Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 32767));
		
		GraphicsEnvironment ge;
		ge = GraphicsEnvironment.getLocalGraphicsEnvironment(); 
		String[] fontNames = ge.getAvailableFontFamilyNames();
		
		setBackground(new java.awt.Color(255, 255, 255));
		setMinimumSize(new java.awt.Dimension(208, 400));
		setPreferredSize(new java.awt.Dimension(208, 512));

		jScrollPane5.setBorder(null);
		jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

		AddNodePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		AddNodeTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		AddNodeTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		AddNodeTitleLabel.setText("Add Node");

		LabelSubtitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		LabelSubtitleLabel.setText("Label");

		LabelTextLabel.setText("Label Text");

		LabelFontLabel.setText("Label Font");

		LabelFontComboBox.setModel(new DefaultComboBoxModel(fontNames));
		LabelFontComboBox.setSelectedItem("Tahoma");

		LabelColorLabel.setText("Label Color");

		LabelColorBtn.setText("[  ]");
		LabelColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

		NodeSubtitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		NodeSubtitleLabel.setText("Node");

		NodeShapeLabel.setText("Node Shape");

		BorderColorLabel.setText("Border Color");

		FillColorLabel.setText("Fill Color");

		FillColorBtn.setText("[  ]");
		FillColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

		NodeShapeComboBox.setModel(new DefaultComboBoxModel(new String[] { "Circle", "Oval", "Square", "Rectangle", "Triangle" }));

		BorderColorBtn.setText("[  ]");
		BorderColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

		jButton1.setText("Add Node");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				AddNodeBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout AddNodePanelLayout = new GroupLayout(AddNodePanel);
		AddNodePanel.setLayout(AddNodePanelLayout);
		AddNodePanelLayout.setHorizontalGroup(
				AddNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(AddNodePanelLayout.createSequentialGroup()
						.addGroup(AddNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(LabelSubtitleLabel)
								.addComponent(NodeSubtitleLabel))
								.addGap(0, 0, Short.MAX_VALUE))
								.addGroup(AddNodePanelLayout.createSequentialGroup()
										.addContainerGap()
										.addGroup(AddNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(AddNodeTitleLabel, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(LabelTextField)
												.addComponent(LabelFontComboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(AddNodePanelLayout.createSequentialGroup()
														.addGroup(AddNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(AddNodePanelLayout.createSequentialGroup()
																		.addGroup(AddNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(LabelTextLabel)
																				.addComponent(LabelFontLabel)
																				.addComponent(BorderColorLabel)
																				.addComponent(FillColorLabel))
																				.addGap(18, 18, 18)
																				.addGroup(AddNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(FillColorBtn)
																						.addComponent(BorderColorBtn)))
																						.addGroup(AddNodePanelLayout.createSequentialGroup()
																								.addGroup(AddNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(NodeShapeLabel)
																										.addComponent(LabelColorLabel))
																										.addGap(18, 18, 18)
																										.addGroup(AddNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(LabelColorBtn)
																												.addComponent(NodeShapeComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
																												.addGap(0, 45, Short.MAX_VALUE))
																												.addComponent(jSeparator1)
																												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddNodePanelLayout.createSequentialGroup()
																														.addGap(0, 0, Short.MAX_VALUE)
																														.addComponent(jButton1)))
																														.addContainerGap())
				);
		AddNodePanelLayout.setVerticalGroup(
				AddNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(AddNodePanelLayout.createSequentialGroup()
						.addComponent(AddNodeTitleLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(LabelSubtitleLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(LabelTextLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(LabelTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(LabelFontLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(LabelFontComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(AddNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(LabelColorLabel)
								.addComponent(LabelColorBtn))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
								.addGap(3, 3, 3)
								.addComponent(NodeSubtitleLabel)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(AddNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(NodeShapeLabel)
										.addComponent(NodeShapeComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(AddNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(BorderColorLabel)
												.addComponent(BorderColorBtn))
												.addGap(18, 18, 18)
												.addGroup(AddNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(FillColorLabel)
														.addComponent(FillColorBtn))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
														.addComponent(jButton1)
														.addContainerGap())
				);

		jScrollPane5.setViewportView(AddNodePanel);

		javax.swing.GroupLayout layout = new GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(filler1, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
								.addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 208, GroupLayout.PREFERRED_SIZE)
								.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 512, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(filler1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0))
				);
	}// </editor-fold>
	
	private void AddNodeBtnActionPerformed(java.awt.event.MouseEvent evt) {
		mainWindowTabbedPane = mainWindow.getMainWindowPane();
		JScrollPane currentPane = (JScrollPane)mainWindowTabbedPane.getSelectedComponent();
		GraphPanel currentPanel = (GraphPanel)currentPane.getViewport().getView();
		Graph currentGraph = currentPanel.mGetGraph();
		int numNodes = currentGraph.mGetNodeList().size();
		
		String nodeLabel;
		
		// Retrieve the node label
		if(LabelTextField.getText().isEmpty()) {
			nodeLabel = "Node" + Integer.toString(numNodes + 1);
		}
		else {
			nodeLabel = LabelTextField.getText();
		}
		
		// (Try to) Add the node
		Node newNode = new Node(Integer.toString(numNodes), nodeLabel, (String)NodeShapeComboBox.getSelectedItem(), null);
		// Set the font
		newNode.mSetFont(Font.decode((String)LabelFontComboBox.getSelectedItem()));
		try {
			currentGraph.mAddNode(currentPanel, newNode);
		} catch (CannotAddNodeException e) {
			e.printStackTrace();
		}

		// Redraw the graph with the new node
		GraphHelper.mDrawForceDirectedGraph(currentPanel);
		currentPanel.repaint();
		int newWidth = GraphHelper.mGetPreferredImageWidth(currentGraph);
		currentPanel.setPreferredSize(new Dimension(newWidth, newWidth));
		currentPane.revalidate();
		mainWindow.resetSidePane();
	}
	// Variables declaration - do not modify
	private JPanel AddNodePanel;
	private JLabel AddNodeTitleLabel;
	private JButton BorderColorBtn;
	private JLabel BorderColorLabel;
	private JButton FillColorBtn;
	private JLabel FillColorLabel;
	private JButton LabelColorBtn;
	private JLabel LabelColorLabel;
	private JComboBox LabelFontComboBox;
	private JLabel LabelFontLabel;
	private JLabel LabelSubtitleLabel;
	private JTextField LabelTextField;
	private JLabel LabelTextLabel;
	private JComboBox NodeShapeComboBox;
	private JLabel NodeShapeLabel;
	private JLabel NodeSubtitleLabel;
	private Box.Filler filler1;
	private JButton jButton1;
	private JScrollPane jScrollPane5;
	private JSeparator jSeparator1;
	
	protected JTabbedPane mainWindowTabbedPane;
	// End of variables declaration
}
