/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package autograph.ui;

import javax.swing.*;

public class EditNodePanel extends JPanel {

    /**
     * Creates new form AddNodePanel
     */
    public EditNodePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        NodeOptionsPanel = new JPanel();
        NodeOptionsTitleLabel = new JLabel();
        LabelTextLabel = new JLabel();
        LabelTextField = new JTextField();
        NodeShapeLabel = new JLabel();
        NodeShapeComboBox = new JComboBox();
        BorderColorLabel = new JLabel();
        BorderColorBtn = new JButton();
        FillColorLabel = new JLabel();
        FillColorBtn = new JButton();
        TextColorLabel = new JLabel();
        TextColorBtn = new JButton();
        filler1 = new Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 32767));

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(200, 300));
        setPreferredSize(new java.awt.Dimension(200, 459));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        NodeOptionsPanel.setPreferredSize(new java.awt.Dimension(200, 457));

        NodeOptionsTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NodeOptionsTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NodeOptionsTitleLabel.setText("Node Options");
        NodeOptionsTitleLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        NodeOptionsTitleLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        LabelTextLabel.setText("Label Text");

        NodeShapeLabel.setText("Node Shape");

        NodeShapeComboBox.setModel(new DefaultComboBoxModel(new String[] { "AA", "BB", "CC", "DD", "EE", "FF" }));

        BorderColorLabel.setText("Border Color");

        BorderColorBtn.setText("[  ]");
        BorderColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

        FillColorLabel.setText("Fill Color");

        FillColorBtn.setText("[  ]");
        FillColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

        TextColorLabel.setText("Text Color");

        TextColorBtn.setText("[  ]");
        TextColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

        GroupLayout NodeOptionsPanelLayout = new GroupLayout(NodeOptionsPanel);
        NodeOptionsPanel.setLayout(NodeOptionsPanelLayout);
        NodeOptionsPanelLayout.setHorizontalGroup(
            NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NodeOptionsTitleLabel, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
            .addGroup(NodeOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTextField)
                    .addGroup(NodeOptionsPanelLayout.createSequentialGroup()
                        .addGroup(NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTextLabel)
                            .addGroup(NodeOptionsPanelLayout.createSequentialGroup()
                                .addGroup(NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextColorLabel)
                                    .addComponent(NodeShapeLabel)
                                    .addComponent(BorderColorLabel)
                                    .addComponent(FillColorLabel))
                                .addGap(18, 18, 18)
                                .addGroup(NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NodeShapeComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TextColorBtn))
                                    .addGroup(NodeOptionsPanelLayout.createSequentialGroup()
                                        .addGroup(NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FillColorBtn)
                                            .addComponent(BorderColorBtn))
                                        .addGap(10, 10, 10)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        NodeOptionsPanelLayout.setVerticalGroup(
            NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NodeOptionsPanelLayout.createSequentialGroup()
                .addComponent(NodeOptionsTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(LabelTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NodeOptionsPanelLayout.createSequentialGroup()
                        .addGroup(NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextColorLabel)
                            .addComponent(TextColorBtn))
                        .addGap(18, 18, 18)
                        .addGroup(NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NodeShapeLabel)
                            .addComponent(NodeShapeComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BorderColorLabel)
                            .addComponent(BorderColorBtn)))
                    .addGroup(NodeOptionsPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FillColorBtn)
                            .addComponent(FillColorLabel))))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(NodeOptionsPanel);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 201, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(filler1, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 457, GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(161, 161, 161)
                    .addComponent(filler1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(298, Short.MAX_VALUE)))
        );
    }// </editor-fold>
    // Variables declaration - do not modify
    private JButton BorderColorBtn;
    private JLabel BorderColorLabel;
    private JButton FillColorBtn;
    private JLabel FillColorLabel;
    private JTextField LabelTextField;
    private JLabel LabelTextLabel;
    private JPanel NodeOptionsPanel;
    private JLabel NodeOptionsTitleLabel;
    private JComboBox NodeShapeComboBox;
    private JLabel NodeShapeLabel;
    private JButton TextColorBtn;
    private JLabel TextColorLabel;
    private Box.Filler filler1;
    private JScrollPane jScrollPane1;
    // End of variables declaration
}
