/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package autograph.ui;

import javax.swing.*;

public class EditNodeEdgePanel extends JPanel {

    /**
     * Creates new form AddNodePanel
     */
    public EditNodeEdgePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane8 = new JScrollPane();
        jPanel7 = new JPanel();
        EditTitleLabel = new JLabel();
        LabelSubtitleLabel = new JLabel();
        LabelTextLabel = new JLabel();
        LabelTextField = new JTextField();
        LabelFontLabel = new JLabel();
        LabelFontComboBox = new JComboBox();
        LabelColorLabel = new JLabel();
        LabelColorBtn = new JButton();
        jSeparator1 = new JSeparator();
        NodeSubtitleLabel = new JLabel();
        NodeShapeLabel = new JLabel();
        NodeShapeComboBox = new JComboBox();
        BorderColorLabel = new JLabel();
        BorderColorBtn = new JButton();
        FillColorLabel = new JLabel();
        FillColorBtn = new JButton();
        jSeparator2 = new JSeparator();
        EdgeSubtitleLabel = new JLabel();
        EdgeDesignLabel = new JLabel();
        EdgeDesignComboBox = new JComboBox();
        EndShapeLabel = new JLabel();
        EndShapeComboBox = new JComboBox();
        EdgeColorLabel = new JLabel();
        EdgeColorBtn = new JButton();
        jButton22 = new JButton();
        filler1 = new Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 32767));

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(200, 300));

        jScrollPane8.setBorder(null);
        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel7.setPreferredSize(new java.awt.Dimension(200, 512));

        EditTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EditTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditTitleLabel.setText("Edit Nodes/Edges");

        LabelSubtitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelSubtitleLabel.setText("Label");

        LabelTextLabel.setText("Label Text");

        LabelFontLabel.setText("Label Font");

        LabelFontComboBox.setModel(new DefaultComboBoxModel(new String[] { "Times New Roman", "Ariel", "Some other font", "More fonts", "Wingdings" }));

        LabelColorLabel.setText("Label Color");

        LabelColorBtn.setText("[  ]");
        LabelColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

        NodeSubtitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NodeSubtitleLabel.setText("Node");

        NodeShapeLabel.setText("Node Shape");

        NodeShapeComboBox.setModel(new DefaultComboBoxModel(new String[] { "AA", "BB", "CC", "DD", "EE", "FF" }));

        BorderColorLabel.setText("Border Color");

        BorderColorBtn.setText("[  ]");
        BorderColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

        FillColorLabel.setText("Fill Color");

        FillColorBtn.setText("[  ]");
        FillColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

        EdgeSubtitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EdgeSubtitleLabel.setText("Edge");

        EdgeDesignLabel.setText("Edge Design");

        EdgeDesignComboBox.setModel(new DefaultComboBoxModel(new String[] { "____", "_ _ _", "- - - -", "......", "===", " " }));

        EndShapeLabel.setText("End Shape");

        EndShapeComboBox.setModel(new DefaultComboBoxModel(new String[] { "A-A", "A-B", "A-C", "B-B", "B-C", "C-C" }));

        EdgeColorLabel.setText("Edge Color");

        EdgeColorBtn.setText("[  ]");
        EdgeColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

        jButton22.setLabel("Save Changes");

        GroupLayout jPanel7Layout = new GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelSubtitleLabel)
                    .addComponent(NodeSubtitleLabel)
                    .addComponent(EdgeSubtitleLabel))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, GroupLayout.Alignment.TRAILING)
                    .addComponent(EditTitleLabel, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelTextField)
                    .addComponent(LabelFontComboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NodeShapeLabel)
                                    .addComponent(LabelColorLabel))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelColorBtn)
                                    .addComponent(NodeShapeComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelTextLabel)
                                    .addComponent(LabelFontLabel)
                                    .addComponent(BorderColorLabel)
                                    .addComponent(FillColorLabel))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FillColorBtn)
                                    .addComponent(BorderColorBtn)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EdgeDesignLabel)
                                    .addComponent(EndShapeLabel)
                                    .addComponent(EdgeColorLabel))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EdgeColorBtn)
                                    .addComponent(EndShapeComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EdgeDesignComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton22)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(EditTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelSubtitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelFontLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelFontComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelColorLabel)
                    .addComponent(LabelColorBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(NodeSubtitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NodeShapeLabel)
                    .addComponent(NodeShapeComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BorderColorLabel)
                    .addComponent(BorderColorBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FillColorLabel)
                    .addComponent(FillColorBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(EdgeSubtitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdgeDesignLabel)
                    .addComponent(EdgeDesignComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EndShapeLabel)
                    .addComponent(EndShapeComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdgeColorLabel)
                    .addComponent(EdgeColorBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton22))
        );

        jScrollPane8.setViewportView(jPanel7);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(filler1, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane8, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane8, GroupLayout.PREFERRED_SIZE, 534, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>
    // Variables declaration - do not modify
    private JButton BorderColorBtn;
    private JLabel BorderColorLabel;
    private JButton EdgeColorBtn;
    private JLabel EdgeColorLabel;
    private JComboBox EdgeDesignComboBox;
    private JLabel EdgeDesignLabel;
    private JLabel EdgeSubtitleLabel;
    private JLabel EditTitleLabel;
    private JComboBox EndShapeComboBox;
    private JLabel EndShapeLabel;
    private JButton FillColorBtn;
    private JLabel FillColorLabel;
    private JButton LabelColorBtn;
    private JLabel LabelColorLabel;
    private JComboBox LabelFontComboBox;
    private JLabel LabelFontLabel;
    private JLabel LabelSubtitleLabel;
    private JTextField LabelTextField;
    private JLabel LabelTextLabel;
    private JComboBox NodeShapeComboBox;
    private JLabel NodeShapeLabel;
    private JLabel NodeSubtitleLabel;
    private Box.Filler filler1;
    private JButton jButton22;
    private JPanel jPanel7;
    private JScrollPane jScrollPane8;
    private JSeparator jSeparator1;
    private JSeparator jSeparator2;
    // End of variables declaration
}
