/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package autograph.ui;

import javax.swing.*;

public class EditEdgePanel extends JPanel {

    /**
     * Creates new form AddNodePanel
     */
    public EditEdgePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        EdgeOptionsPanel = new JPanel();
        EdgeOptionsTitleLabel = new JLabel();
        LabelTextLabel = new JLabel();
        LabelTextField = new JTextField();
        TextColorLabel = new JLabel();
        EdgeDesignComboBox = new JComboBox();
        EndShapeLabel = new JLabel();
        EndShapeComboBox = new JComboBox();
        EdgeColorLabel = new JLabel();
        EdgeColorBtn = new JButton();
        EdgeDesignLabel = new JLabel();
        TextColorBtn = new JButton();
        filler1 = new Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 32767));

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(200, 300));
        setPreferredSize(new java.awt.Dimension(200, 459));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        EdgeOptionsPanel.setPreferredSize(new java.awt.Dimension(200, 457));

        EdgeOptionsTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EdgeOptionsTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EdgeOptionsTitleLabel.setText("Edge Options");
        EdgeOptionsTitleLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        EdgeOptionsTitleLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        LabelTextLabel.setText("Label Text");

        TextColorLabel.setText("Text Color");

        EdgeDesignComboBox.setModel(new DefaultComboBoxModel(new String[] { "____", "_ _ _", "- - - -", "......", "===", " " }));

        EndShapeLabel.setText("End Shape");

        EndShapeComboBox.setModel(new DefaultComboBoxModel(new String[] { "A-A", "A-B", "A-C", "B-B", "B-C", "C-C" }));

        EdgeColorLabel.setText("Edge Color");

        EdgeColorBtn.setText("[  ]");
        EdgeColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

        EdgeDesignLabel.setText("Edge Design");

        TextColorBtn.setText("[  ]");
        TextColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

        GroupLayout EdgeOptionsPanelLayout = new GroupLayout(EdgeOptionsPanel);
        EdgeOptionsPanel.setLayout(EdgeOptionsPanelLayout);
        EdgeOptionsPanelLayout.setHorizontalGroup(
            EdgeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EdgeOptionsTitleLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(EdgeOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EdgeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EdgeOptionsPanelLayout.createSequentialGroup()
                        .addGroup(EdgeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextColorLabel)
                            .addComponent(EndShapeLabel)
                            .addComponent(EdgeColorLabel)
                            .addComponent(EdgeDesignLabel))
                        .addGap(18, 18, 18)
                        .addGroup(EdgeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EndShapeComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(EdgeColorBtn)
                            .addComponent(EdgeDesignComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextColorBtn))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(EdgeOptionsPanelLayout.createSequentialGroup()
                        .addGroup(EdgeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTextField)
                            .addGroup(EdgeOptionsPanelLayout.createSequentialGroup()
                                .addComponent(LabelTextLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        EdgeOptionsPanelLayout.setVerticalGroup(
            EdgeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EdgeOptionsPanelLayout.createSequentialGroup()
                .addComponent(EdgeOptionsTitleLabel, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(EdgeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EdgeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextColorLabel)
                        .addComponent(TextColorBtn))
                    .addGroup(EdgeOptionsPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(EdgeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EndShapeComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(EndShapeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(EdgeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EdgeColorBtn)
                            .addComponent(EdgeColorLabel))
                        .addGap(18, 18, 18)
                        .addGroup(EdgeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EdgeDesignComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(EdgeDesignLabel))))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(EdgeOptionsPanel);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 201, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(filler1, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(161, 161, 161)
                    .addComponent(filler1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(298, Short.MAX_VALUE)))
        );
    }// </editor-fold>
    // Variables declaration - do not modify
    private JButton EdgeColorBtn;
    private JLabel EdgeColorLabel;
    private JComboBox EdgeDesignComboBox;
    private JLabel EdgeDesignLabel;
    private JPanel EdgeOptionsPanel;
    private JLabel EdgeOptionsTitleLabel;
    private JComboBox EndShapeComboBox;
    private JLabel EndShapeLabel;
    private JTextField LabelTextField;
    private JLabel LabelTextLabel;
    private JButton TextColorBtn;
    private JLabel TextColorLabel;
    private Box.Filler filler1;
    private JScrollPane jScrollPane1;
    // End of variables declaration
}
