/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package autograph.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

import autograph.Edge;
import autograph.Graph;
import autograph.GraphHelper;
import autograph.Node;
import autograph.GraphPanel;

public class mainWindow extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
       
        MainWindowToolBar = new javax.swing.JToolBar();
        AddNodeBtn = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(25, 0));
        AddEdgeBtn = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(100, 0));
        AutoLabelNodesTog = new javax.swing.JToggleButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(25, 0));
        AutoLabelEdgesTog = new javax.swing.JToggleButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(25, 0));
        AutoConnectNodesTog = new javax.swing.JToggleButton();
        MainWindowTabbedPane = new javax.swing.JTabbedPane();
        

        jPanel2 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 32767));
        jScrollPane5 = new javax.swing.JScrollPane();
        EditPanel = new javax.swing.JPanel();
        EditTitleLabel = new javax.swing.JLabel();
        LabelSubtitleLabel = new javax.swing.JLabel();
        LabelTextLabel = new javax.swing.JLabel();
        LabelTextField = new javax.swing.JTextField();
        LabelFontLabel = new javax.swing.JLabel();
        LabelFontComboBox = new javax.swing.JComboBox();
        LabelColorLabel = new javax.swing.JLabel();
        LabelColorBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        NodeSubtitleLabel = new javax.swing.JLabel();
        NodeShapeLabel = new javax.swing.JLabel();
        NodeShapeComboBox = new javax.swing.JComboBox();
        BorderColorLabel = new javax.swing.JLabel();
        BorderColorBtn = new javax.swing.JButton();
        FillColorLabel = new javax.swing.JLabel();
        FillColorBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        EdgeSubtitleLabel = new javax.swing.JLabel();
        EdgeDesignLabel = new javax.swing.JLabel();
        EdgeDesignComboBox = new javax.swing.JComboBox();
        EndShapeLabel = new javax.swing.JLabel();
        EndShapeComboBox = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        MainWindowMenuBar = new javax.swing.JMenuBar();
        FileDropdownMenu = new javax.swing.JMenu();
        NewGraphMenuItem = new javax.swing.JMenuItem();
        OpenMenuItem = new javax.swing.JMenuItem();
        SaveMenuItem = new javax.swing.JMenuItem();
        SaveAsMenuItem = new javax.swing.JMenuItem();
        PrintMenuItem = new javax.swing.JMenuItem();
        PrintPreviewMenuItem = new javax.swing.JMenuItem();
        CloseGraphMenuItem = new javax.swing.JMenuItem();
        ExitMenuItem = new javax.swing.JMenuItem();
        EditDropdownMenu = new javax.swing.JMenu();
        SelectAllMenuItem = new javax.swing.JMenuItem();
        SelectAllNodesMenuItem = new javax.swing.JMenuItem();
        SelectAllEdgesMenuItem = new javax.swing.JMenuItem();
        DeselectMenuItem = new javax.swing.JMenuItem();
        ViewDropdownMenu = new javax.swing.JMenu();
        CloseTabMenuItem = new javax.swing.JMenuItem();
        CloseAllOtherTabsMenuItem = new javax.swing.JMenuItem();
        OpenAdvancedCodeViewMenuItem = new javax.swing.JMenuItem();
        ToolsDropdownMenu = new javax.swing.JMenu();
        AutoLabelNodesMenuItem = new javax.swing.JCheckBoxMenuItem();
        AutoLabelEdgesMenuItem = new javax.swing.JCheckBoxMenuItem();
        AutoConnectNodesMenuItem = new javax.swing.JCheckBoxMenuItem();
        ChangeBgColorMenuItem = new javax.swing.JMenuItem();
        HelpDropdownMenu = new javax.swing.JMenu();
        ViewUserGuideMenuItem = new javax.swing.JMenuItem();
        AboutAutographMenuItem = new javax.swing.JMenuItem();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));

        MainWindowToolBar.setFloatable(false);
        MainWindowToolBar.setRollover(true);

        Icon addIcon = new ImageIcon("resources/AddNode.png");
        AddNodeBtn.setIcon(addIcon);
        AddNodeBtn.setText("Add Node");
        AddNodeBtn.setFocusable(false);
        AddNodeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddNodeBtn.setMargin(new java.awt.Insets(5, 5, 2, 5));
        AddNodeBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AddNodeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNodeBtnActionPerformed(evt);
            }
        });
        MainWindowToolBar.add(AddNodeBtn);
        MainWindowToolBar.add(filler3);

        Icon edgeIcon = new ImageIcon("resources/AddEdge.png");
        AddEdgeBtn.setIcon(edgeIcon);
        AddEdgeBtn.setText("Add Edge");
        AddEdgeBtn.setFocusable(false);
        AddEdgeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddEdgeBtn.setMargin(new java.awt.Insets(5, 5, 2, 5));
        AddEdgeBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MainWindowToolBar.add(AddEdgeBtn);
        MainWindowToolBar.add(filler2);

        Icon ALNTIcon = new ImageIcon("resources/ToggleOn.png");
        AutoLabelNodesTog.setIcon(ALNTIcon);
        AutoLabelNodesTog.setSelected(true);
        AutoLabelNodesTog.setText("Auto-Label Nodes");
        AutoLabelNodesTog.setFocusable(false);
        AutoLabelNodesTog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoLabelNodesTogActionPerformed(evt);
            }
        });
        MainWindowToolBar.add(AutoLabelNodesTog);
        MainWindowToolBar.add(filler4);

        Icon ALETIcon = new ImageIcon("resources/ToggleOff.png");
        AutoLabelEdgesTog.setIcon(ALETIcon);
        AutoLabelEdgesTog.setText("Auto-Label Edges");
        AutoLabelEdgesTog.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AutoLabelEdgesTog.setFocusable(false);
        AutoLabelEdgesTog.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AutoLabelEdgesTog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoLabelEdgesTogActionPerformed(evt);
            }
        });
        MainWindowToolBar.add(AutoLabelEdgesTog);
        MainWindowToolBar.add(filler5);

        Icon ACNTIcon = new ImageIcon("resources/ToggleOff.png");
        AutoConnectNodesTog.setIcon(ACNTIcon);
        AutoConnectNodesTog.setText("Auto-Connect Nodes");
        AutoConnectNodesTog.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AutoConnectNodesTog.setFocusable(false);
        AutoConnectNodesTog.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MainWindowToolBar.add(AutoConnectNodesTog);

        MainWindowTabbedPane.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        MainWindowTabbedPane.setMinimumSize(new java.awt.Dimension(114, 95));

        
        if(vTabs == null){
        	vTabs = new ArrayList<JScrollPane>();
        }
        if(vTabs.isEmpty()){
        	String filePath = "Graph.txt";
            Graph graph = GraphHelper.mImportGraphFromGML(filePath, null);
	        GraphTabPane = new javax.swing.JScrollPane();
	        GraphTabSubPane = new GraphPanel(graph);
	        GraphTabPane.setBorder(null);
	
	        GraphTabSubPane.setBackground(new java.awt.Color(255, 255, 255));
	        GraphTabSubPane.setPreferredSize(new java.awt.Dimension(600, 400));
	
	        javax.swing.GroupLayout GraphTabSubPaneLayout = new javax.swing.GroupLayout(GraphTabSubPane);
	        GraphTabSubPane.setLayout(GraphTabSubPaneLayout);
	        GraphTabSubPaneLayout.setHorizontalGroup(
	            GraphTabSubPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 912, Short.MAX_VALUE)
	        );
	        GraphTabSubPaneLayout.setVerticalGroup(
	            GraphTabSubPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 476, Short.MAX_VALUE)
	        );
	
	        GraphTabPane.setViewportView(GraphTabSubPane);
	
	        MainWindowTabbedPane.addTab("New Graph", GraphTabPane);
	
	        //KMW Note: This is going to be our way of keeping track of tabs. We will initialize with
	        //          one blank tab on startup.
	        vTabs.add(GraphTabPane);
        }
        

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        EditPanel.setPreferredSize(new java.awt.Dimension(200, 512));

        EditTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EditTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditTitleLabel.setText("Edit Nodes/Edges");

        LabelSubtitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelSubtitleLabel.setText("Label");

        LabelTextLabel.setText("Label Text");

        LabelFontLabel.setText("Label Font");

        LabelFontComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Times New Roman", "Ariel", "Some other font", "More fonts", "Wingdings" }));

        LabelColorLabel.setText("Label Color");

        Icon LCBIcon = new ImageIcon("resources/ColorBlack.png");
        LabelColorBtn.setIcon(LCBIcon);
        LabelColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

        NodeSubtitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NodeSubtitleLabel.setText("Node");

        NodeShapeLabel.setText("Node Shape");

        NodeShapeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AA", "BB", "CC", "DD", "EE", "FF" }));

        BorderColorLabel.setText("Border Color");

        Icon BCBIcon = new ImageIcon("resources/ColorBlack.png");
        BorderColorBtn.setIcon(BCBIcon);
        BorderColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

        FillColorLabel.setText("Fill Color");

        Icon FCBIcon = new ImageIcon("resources/ColorWhite.png");
        FillColorBtn.setIcon(FCBIcon);
        FillColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

        EdgeSubtitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EdgeSubtitleLabel.setText("Edge");
        EdgeSubtitleLabel.setEnabled(false);

        EdgeDesignLabel.setText("Edge Design");
        EdgeDesignLabel.setEnabled(false);

        EdgeDesignComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- - - -", "......", "===", " " }));
        EdgeDesignComboBox.setEnabled(false);

        EndShapeLabel.setText("End Shape");
        EndShapeLabel.setEnabled(false);

        EndShapeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A-A", "A-B", "A-C", "B-B", "B-C", "C-C" }));
        EndShapeComboBox.setEnabled(false);

        jLabel13.setText("Edge Color");
        jLabel13.setEnabled(false);

        Icon jB8Icon = new ImageIcon("resources/ColorBlue.png");
        jButton8.setIcon(jB8Icon);
        jButton8.setEnabled(false);
        jButton8.setMargin(new java.awt.Insets(2, 5, 2, 5));

        jButton9.setLabel("Save Changes");

        javax.swing.GroupLayout EditPanelLayout = new javax.swing.GroupLayout(EditPanel);
        EditPanel.setLayout(EditPanelLayout);
        EditPanelLayout.setHorizontalGroup(
            EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPanelLayout.createSequentialGroup()
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelSubtitleLabel)
                    .addComponent(NodeSubtitleLabel)
                    .addComponent(EdgeSubtitleLabel))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(EditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EditTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelTextField)
                    .addComponent(LabelFontComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(EditPanelLayout.createSequentialGroup()
                        .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditPanelLayout.createSequentialGroup()
                                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NodeShapeLabel)
                                    .addComponent(LabelColorLabel))
                                .addGap(26, 26, 26)
                                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelColorBtn)
                                    .addComponent(NodeShapeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EditPanelLayout.createSequentialGroup()
                                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelTextLabel)
                                    .addComponent(LabelFontLabel)
                                    .addComponent(BorderColorLabel)
                                    .addComponent(FillColorLabel))
                                .addGap(24, 24, 24)
                                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FillColorBtn)
                                    .addComponent(BorderColorBtn)))
                            .addGroup(EditPanelLayout.createSequentialGroup()
                                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EdgeDesignLabel)
                                    .addComponent(EndShapeLabel)
                                    .addComponent(jLabel13))
                                .addGap(25, 25, 25)
                                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8)
                                    .addComponent(EndShapeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EdgeDesignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton9)))
                .addContainerGap())
        );
        EditPanelLayout.setVerticalGroup(
            EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPanelLayout.createSequentialGroup()
                .addComponent(EditTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelSubtitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelFontLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelFontComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelColorLabel)
                    .addComponent(LabelColorBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(NodeSubtitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NodeShapeLabel)
                    .addComponent(NodeShapeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BorderColorLabel)
                    .addComponent(BorderColorBtn))
                .addGap(18, 18, 18)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FillColorLabel)
                    .addComponent(FillColorBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(EdgeSubtitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdgeDesignLabel)
                    .addComponent(EdgeDesignComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EndShapeLabel)
                    .addComponent(EndShapeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9))
        );

        jScrollPane5.setViewportView(EditPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(filler1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        FileDropdownMenu.setText("File");

        NewGraphMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        NewGraphMenuItem.setText("New Graph...");
        NewGraphMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGraphMenuItemActionPerformed(evt);
            }
        });
        FileDropdownMenu.add(NewGraphMenuItem);

        OpenMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OpenMenuItem.setText("Open...");
        FileDropdownMenu.add(OpenMenuItem);

        SaveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveMenuItem.setText("Save");
        FileDropdownMenu.add(SaveMenuItem);

        SaveAsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        SaveAsMenuItem.setText("Save As...");
        FileDropdownMenu.add(SaveAsMenuItem);

        PrintMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        PrintMenuItem.setText("Print...");
        FileDropdownMenu.add(PrintMenuItem);

        PrintPreviewMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        PrintPreviewMenuItem.setText("Print Preview");
        FileDropdownMenu.add(PrintPreviewMenuItem);

        CloseGraphMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        CloseGraphMenuItem.setText("Close Graph");
        FileDropdownMenu.add(CloseGraphMenuItem);

        ExitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        ExitMenuItem.setText("Exit");
        FileDropdownMenu.add(ExitMenuItem);

        MainWindowMenuBar.add(FileDropdownMenu);

        EditDropdownMenu.setText("Edit");

        SelectAllMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        SelectAllMenuItem.setText("Select All");
        SelectAllMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectAllMenuItemActionPerformed(evt);
            }
        });
        EditDropdownMenu.add(SelectAllMenuItem);

        SelectAllNodesMenuItem.setText("Select All Nodes");
        EditDropdownMenu.add(SelectAllNodesMenuItem);

        SelectAllEdgesMenuItem.setText("Select All Edges");
        EditDropdownMenu.add(SelectAllEdgesMenuItem);

        DeselectMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        DeselectMenuItem.setText("Deselect");
        EditDropdownMenu.add(DeselectMenuItem);

        MainWindowMenuBar.add(EditDropdownMenu);

        ViewDropdownMenu.setText("View");

        CloseTabMenuItem.setText("Close Tab");
        CloseTabMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseTabMenuItemActionPerformed(evt);
            }
        });
        ViewDropdownMenu.add(CloseTabMenuItem);

        CloseAllOtherTabsMenuItem.setText("Close All Other Tabs");
        ViewDropdownMenu.add(CloseAllOtherTabsMenuItem);

        OpenAdvancedCodeViewMenuItem.setText("Open Advanced Code View");
        ViewDropdownMenu.add(OpenAdvancedCodeViewMenuItem);

        MainWindowMenuBar.add(ViewDropdownMenu);

        ToolsDropdownMenu.setText("Tools");

        AutoLabelNodesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        AutoLabelNodesMenuItem.setSelected(true);
        AutoLabelNodesMenuItem.setText("Auto-Label Nodes");
        AutoLabelNodesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoLabelNodesMenuItemActionPerformed(evt);
            }
        });
        ToolsDropdownMenu.add(AutoLabelNodesMenuItem);

        AutoLabelEdgesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        AutoLabelEdgesMenuItem.setText("Auto-Label Edges");
        ToolsDropdownMenu.add(AutoLabelEdgesMenuItem);

        AutoConnectNodesMenuItem.setText("Auto-Connect Nodes");
        AutoConnectNodesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoConnectNodesMenuItemActionPerformed(evt);
            }
        });
        ToolsDropdownMenu.add(AutoConnectNodesMenuItem);

        ChangeBgColorMenuItem.setText("Change Background Color");
        ToolsDropdownMenu.add(ChangeBgColorMenuItem);

        MainWindowMenuBar.add(ToolsDropdownMenu);

        HelpDropdownMenu.setText("Help");

        ViewUserGuideMenuItem.setText("View User Guide");
        HelpDropdownMenu.add(ViewUserGuideMenuItem);

        AboutAutographMenuItem.setText("About Autograph...");
        HelpDropdownMenu.add(AboutAutographMenuItem);

        MainWindowMenuBar.add(HelpDropdownMenu);

        setJMenuBar(MainWindowMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MainWindowTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(MainWindowToolBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainWindowToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainWindowTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AutoLabelNodesTogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoLabelNodesTogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutoLabelNodesTogActionPerformed

    private void AutoLabelEdgesTogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoLabelEdgesTogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutoLabelEdgesTogActionPerformed

    /**
     * Opens a new tab on the main window with an empty graph.
     * @param evt
     */
    private void NewGraphMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGraphMenuItemActionPerformed
    	//first get a unique title for the new tab
    	String newTitle = "New Graph";
    	Boolean uniqueTitle = false;
    	int currentNum = 1;
    	while(!uniqueTitle){
    		//loop through each tab and check the titles.
    		for(int i = 0; i < vTabs.size(); i++){
    			GraphPanel panel = (GraphPanel)vTabs.get(i).getViewport().getView();
    			//check the current tab has the same name as the new title we are creating
    			if(panel.mGetGraph().mGetTitle().compareTo(newTitle) == 0){
    				//if it does reset newTitle to be of the form "New Graph[1]"
    				newTitle = "New Graph[" + currentNum + "]";
    				currentNum++;
    				break;
    			}
    			if(i == vTabs.size() - 1){
    				//if we get here then we have gone through the whole list and not found
    				//a duplicate title, so we will break out of the while loop.
    				uniqueTitle = true;
    			}
    		}
    	}
    	//KMW Note: We are simply creating a new blank tab right now. We do not need to worry
    	//          about drawing any graphs in this function.
    	Graph newGraph = new Graph(newTitle);
    	GraphHelper.mImportGraphFromXML("Graph.xml");
    	JScrollPane newPane = new javax.swing.JScrollPane();
        GraphPanel newGraphPanel = new GraphPanel(newGraph);
        newPane.setBorder(null);

        newGraphPanel.setBackground(new java.awt.Color(255, 255, 255));
        newGraphPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        newPane.setViewportView(newGraphPanel);
        
        javax.swing.GroupLayout newGraphPanelLayout = new javax.swing.GroupLayout(newGraphPanel);
        newGraphPanel.setLayout(newGraphPanelLayout);
        newGraphPanelLayout.setHorizontalGroup(
            newGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        newGraphPanelLayout.setVerticalGroup(
            newGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        MainWindowTabbedPane.addTab(newTitle, newPane);

        //KMW Note: This is going to be our way of keeping track of tabs. We will initialize with
        //          one blank tab on startup.
        vTabs.add(newPane);
    }//GEN-LAST:event_NewGraphMenuItemActionPerformed

    private void SelectAllMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectAllMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectAllMenuItemActionPerformed

    private void CloseTabMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseTabMenuItemActionPerformed
        //
    }//GEN-LAST:event_CloseTabMenuItemActionPerformed

    private void AutoLabelNodesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoLabelNodesMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutoLabelNodesMenuItemActionPerformed

    private void AutoConnectNodesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoConnectNodesMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutoConnectNodesMenuItemActionPerformed

    private void AddNodeBtnActionPerformed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNodeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddNodeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutAutographMenuItem;
    private javax.swing.JButton AddEdgeBtn;
    private javax.swing.JButton AddNodeBtn;
    private javax.swing.JCheckBoxMenuItem AutoConnectNodesMenuItem;
    private javax.swing.JToggleButton AutoConnectNodesTog;
    private javax.swing.JCheckBoxMenuItem AutoLabelEdgesMenuItem;
    private javax.swing.JToggleButton AutoLabelEdgesTog;
    private javax.swing.JCheckBoxMenuItem AutoLabelNodesMenuItem;
    private javax.swing.JToggleButton AutoLabelNodesTog;
    private javax.swing.JButton BorderColorBtn;
    private javax.swing.JLabel BorderColorLabel;
    private javax.swing.JMenuItem ChangeBgColorMenuItem;
    private javax.swing.JMenuItem CloseAllOtherTabsMenuItem;
    private javax.swing.JMenuItem CloseGraphMenuItem;
    private javax.swing.JMenuItem CloseTabMenuItem;
    private javax.swing.JMenuItem DeselectMenuItem;
    private javax.swing.JComboBox EdgeDesignComboBox;
    private javax.swing.JLabel EdgeDesignLabel;
    private javax.swing.JLabel EdgeSubtitleLabel;
    private javax.swing.JMenu EditDropdownMenu;
    private javax.swing.JPanel EditPanel;
    private javax.swing.JLabel EditTitleLabel;
    private javax.swing.JComboBox EndShapeComboBox;
    private javax.swing.JLabel EndShapeLabel;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JMenu FileDropdownMenu;
    private javax.swing.JButton FillColorBtn;
    private javax.swing.JLabel FillColorLabel;
    private javax.swing.JMenu HelpDropdownMenu;
    private javax.swing.JButton LabelColorBtn;
    private javax.swing.JLabel LabelColorLabel;
    private javax.swing.JComboBox LabelFontComboBox;
    private javax.swing.JLabel LabelFontLabel;
    private javax.swing.JLabel LabelSubtitleLabel;
    private javax.swing.JTextField LabelTextField;
    private javax.swing.JLabel LabelTextLabel;
    private javax.swing.JMenuBar MainWindowMenuBar;
    private javax.swing.JTabbedPane MainWindowTabbedPane;
    private javax.swing.JToolBar MainWindowToolBar;
    private javax.swing.JMenuItem NewGraphMenuItem;
    private javax.swing.JComboBox NodeShapeComboBox;
    private javax.swing.JLabel NodeShapeLabel;
    private javax.swing.JLabel NodeSubtitleLabel;
    private javax.swing.JMenuItem OpenAdvancedCodeViewMenuItem;
    private javax.swing.JMenuItem OpenMenuItem;
    private javax.swing.JMenuItem PrintMenuItem;
    private javax.swing.JMenuItem PrintPreviewMenuItem;
    private javax.swing.JMenuItem SaveAsMenuItem;
    private javax.swing.JMenuItem SaveMenuItem;
    private javax.swing.JMenuItem SelectAllEdgesMenuItem;
    private javax.swing.JMenuItem SelectAllMenuItem;
    private javax.swing.JMenuItem SelectAllNodesMenuItem;
    //private javax.swing.JScrollPane TabAreaScrollPane;
    private javax.swing.JMenu ToolsDropdownMenu;
    private javax.swing.JMenu ViewDropdownMenu;
    private javax.swing.JMenuItem ViewUserGuideMenuItem;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel2;
    public GraphPanel GraphTabSubPane;
    //private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane GraphTabPane;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    
    public ArrayList<JScrollPane> vTabs;
    // End of variables declaration//GEN-END:variables
}


