/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package autograph.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileFilter;
import java.util.ArrayList;

import javax.swing.*;

import autograph.Edge;
import autograph.Graph;
import autograph.GraphHelper;
import autograph.Node;
import autograph.GraphPanel;
import autograph.exception.CannotAddNodeException;

/*
 * JMF - NOTE - I COMMENTED OUT ALL THE EDIT PANEL STUFF BECAUSE IT SERVES NO FUNCTION!
 * 			  - ALL SIDE PANELS HAVE THEIR OWN CLASSES - THE ONE HERE WAS JUST FOR SHOW!
 * 			  - I COMMENTED IT OUT INSTEAD OF DELETING IN CASE WE NEED TO REFERENCE IT 
 * 			  - FOR SIZING VALUES FOR THE OTHER PANELS!
 */

public class mainWindow extends JFrame {

	/**
	 * Creates new form mainWindow
	 */
	public mainWindow() {
		initComponents();
	}

	public void exit() { 
		setVisible(false); 
		dispose(); 
		System.exit(0); 
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		MainWindowToolBar = new JToolBar();
		AddNodeBtn = new JButton();
		filler3 = new Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(25, 0));
		AddEdgeBtn = new JButton();
		filler2 = new Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(100, 0));
		AutoLabelNodesTog = new JToggleButton();
		filler4 = new Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(25, 0));
		AutoLabelEdgesTog = new JToggleButton();
		filler5 = new Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(25, 0));
		AutoConnectNodesTog = new JToggleButton();
		MainWindowTabbedPane = new JTabbedPane();

		// The side panels
		addNodePanel = new AddNodePanel();
		addEdgePanel = new AddEdgePanel();
		editNodePanel = new EditNodePanel();
		editEdgePanel = new EditEdgePanel();
		editNodeEdgePanel = new EditNodeEdgePanel();		

		jPanel2 = new JPanel();
		filler1 = new Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 32767));
		sidePanelScrollPane = new JScrollPane();
		EditPanel = new JPanel();
		/*
		EditTitleLabel = new JLabel();
		LabelSubtitleLabel = new JLabel();
		LabelTextLabel = new JLabel();
		LabelTextField = new JTextField();
		LabelFontLabel = new JLabel();
		LabelFontComboBox = new JComboBox();
		LabelColorLabel = new JLabel();
		LabelColorBtn = new JButton();
		jSeparator1 = new JSeparator();
		NodeSubtitleLabel = new JLabel();
		NodeShapeLabel = new JLabel();
		NodeShapeComboBox = new JComboBox();
		BorderColorLabel = new JLabel();
		BorderColorBtn = new JButton();
		FillColorLabel = new JLabel();
		FillColorBtn = new JButton();
		jSeparator2 = new JSeparator();
		EdgeSubtitleLabel = new JLabel();
		EdgeDesignLabel = new JLabel();
		EdgeDesignComboBox = new JComboBox();
		EndShapeLabel = new JLabel();
		EndShapeComboBox = new JComboBox();
		jLabel13 = new JLabel();
		jButton8 = new JButton();
		jButton9 = new JButton();*/
		MainWindowMenuBar = new JMenuBar();
		FileDropdownMenu = new JMenu();
		NewGraphMenuItem = new JMenuItem();
		OpenMenuItem = new JMenuItem();
		SaveMenuItem = new JMenuItem();
		SaveAsMenuItem = new JMenuItem();
		PrintMenuItem = new JMenuItem();
		PrintPreviewMenuItem = new JMenuItem();
		CloseGraphMenuItem = new JMenuItem();
		ExitMenuItem = new JMenuItem();
		EditDropdownMenu = new JMenu();
		SelectAllMenuItem = new JMenuItem();
		SelectAllNodesMenuItem = new JMenuItem();
		SelectAllEdgesMenuItem = new JMenuItem();
		DeselectMenuItem = new JMenuItem();
		ViewDropdownMenu = new JMenu();
		CloseTabMenuItem = new JMenuItem();
		CloseAllOtherTabsMenuItem = new JMenuItem();
		OpenAdvancedCodeViewMenuItem = new JMenuItem();
		ToolsDropdownMenu = new JMenu();
		AutoLabelNodesMenuItem = new JCheckBoxMenuItem();
		AutoLabelEdgesMenuItem = new JCheckBoxMenuItem();
		AutoConnectNodesMenuItem = new JCheckBoxMenuItem();
		ChangeBgColorMenuItem = new JMenuItem();
		HelpDropdownMenu = new JMenu();
		ViewUserGuideMenuItem = new JMenuItem();
		AboutAutographMenuItem = new JMenuItem();


		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(800, 600));

		MainWindowToolBar.setFloatable(false);
		MainWindowToolBar.setRollover(true);

		Icon addIcon = new ImageIcon("resources/AddNode.png");
		AddNodeBtn.setIcon(addIcon);
		AddNodeBtn.setText("Add Node");
		AddNodeBtn.setFocusable(false);
		AddNodeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		AddNodeBtn.setMargin(new java.awt.Insets(5, 5, 2, 5));
		AddNodeBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		AddNodeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				AddNodeBtnActionPerformed(evt);
			}
		});
		MainWindowToolBar.add(AddNodeBtn);
		MainWindowToolBar.add(filler3);

		Icon edgeIcon = new ImageIcon("resources/AddEdge.png");
		AddEdgeBtn.setIcon(edgeIcon);
		AddEdgeBtn.setText("Add Edge");
		AddEdgeBtn.setFocusable(false);
		AddEdgeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		AddEdgeBtn.setMargin(new java.awt.Insets(5, 5, 2, 5));
		AddEdgeBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		AddEdgeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				AddEdgeBtnActionPerformed(evt);
			}
		});
		MainWindowToolBar.add(AddEdgeBtn);
		MainWindowToolBar.add(filler2);

		Icon ALNTIcon = new ImageIcon("resources/ToggleOn.png");
		AutoLabelNodesTog.setIcon(ALNTIcon);
		AutoLabelNodesTog.setSelected(true);
		AutoLabelNodesTog.setText("Auto-Label Nodes");
		AutoLabelNodesTog.setFocusable(false);
		AutoLabelNodesTog.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AutoLabelNodesTogActionPerformed(evt);
			}
		});
		MainWindowToolBar.add(AutoLabelNodesTog);
		MainWindowToolBar.add(filler4);

		Icon ALETIcon = new ImageIcon("resources/ToggleOff.png");
		AutoLabelEdgesTog.setIcon(ALETIcon);
		AutoLabelEdgesTog.setText("Auto-Label Edges");
		AutoLabelEdgesTog.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		AutoLabelEdgesTog.setFocusable(false);
		AutoLabelEdgesTog.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		AutoLabelEdgesTog.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AutoLabelEdgesTogActionPerformed(evt);
			}
		});
		MainWindowToolBar.add(AutoLabelEdgesTog);
		MainWindowToolBar.add(filler5);

		Icon ACNTIcon = new ImageIcon("resources/ToggleOff.png");
		AutoConnectNodesTog.setIcon(ACNTIcon);
		AutoConnectNodesTog.setText("Auto-Connect Nodes");
		AutoConnectNodesTog.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		AutoConnectNodesTog.setFocusable(false);
		AutoConnectNodesTog.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		MainWindowToolBar.add(AutoConnectNodesTog);

		MainWindowTabbedPane.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
		MainWindowTabbedPane.setMinimumSize(new java.awt.Dimension(114, 95));

		String filePath = "Graph.xml";
		//Graph graph = new Graph("Original Tab");
		Graph graph = GraphHelper.mImportGraphFromXML(filePath);
		GraphTabPane = new JScrollPane();
		GraphTabSubPane = new GraphPanel(graph);
		GraphTabPane.setBorder(null);

		GraphTabSubPane.setBackground(new java.awt.Color(255, 255, 255));
		GraphTabSubPane.setPreferredSize(new java.awt.Dimension(600, 600));

		javax.swing.GroupLayout GraphTabSubPaneLayout = new GroupLayout(GraphTabSubPane);
		GraphTabSubPane.setLayout(GraphTabSubPaneLayout);
		GraphTabSubPaneLayout.setHorizontalGroup(
				GraphTabSubPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 912, Short.MAX_VALUE)
				);
		GraphTabSubPaneLayout.setVerticalGroup(
				GraphTabSubPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 476, Short.MAX_VALUE)
				);

		GraphTabPane.setViewportView(GraphTabSubPane);

		MainWindowTabbedPane.addTab("Original Tab", GraphTabPane);

		addNodePanel.setPreferredSize(new java.awt.Dimension(200, 512));
		addEdgePanel.setPreferredSize(new java.awt.Dimension(200, 512));
		editNodePanel.setPreferredSize(new java.awt.Dimension(200, 512));
		editEdgePanel.setPreferredSize(new java.awt.Dimension(200, 512));
		editNodeEdgePanel.setPreferredSize(new java.awt.Dimension(200, 512));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		sidePanelScrollPane.setBorder(null);
		sidePanelScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

		EditPanel.setPreferredSize(new java.awt.Dimension(200, 512));

		/*
		
		EditTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		EditTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		EditTitleLabel.setText("Edit Nodes/Edges");

		LabelSubtitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		LabelSubtitleLabel.setText("Label");

		LabelTextLabel.setText("Label Text");

		LabelFontLabel.setText("Label Font");

		LabelFontComboBox.setModel(new DefaultComboBoxModel(new String[] { "Times New Roman", "Ariel", "Some other font", "More fonts", "Wingdings" }));

		LabelColorLabel.setText("Label Color");

		Icon LCBIcon = new ImageIcon("resources/ColorBlack.png");
		LabelColorBtn.setIcon(LCBIcon);
		LabelColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

		NodeSubtitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		NodeSubtitleLabel.setText("Node");

		NodeShapeLabel.setText("Node Shape");

		NodeShapeComboBox.setModel(new DefaultComboBoxModel(new String[] { "AA", "BB", "CC", "DD", "EE", "FF" }));

		BorderColorLabel.setText("Border Color");

		Icon BCBIcon = new ImageIcon("resources/ColorBlack.png");
		BorderColorBtn.setIcon(BCBIcon);
		BorderColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

		FillColorLabel.setText("Fill Color");

		Icon FCBIcon = new ImageIcon("resources/ColorWhite.png");
		FillColorBtn.setIcon(FCBIcon);
		FillColorBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));

		EdgeSubtitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		EdgeSubtitleLabel.setText("Edge");
		EdgeSubtitleLabel.setEnabled(false);

		EdgeDesignLabel.setText("Edge Design");
		EdgeDesignLabel.setEnabled(false);

		EdgeDesignComboBox.setModel(new DefaultComboBoxModel(new String[] { "- - - -", "......", "===", " " }));
		EdgeDesignComboBox.setEnabled(false);

		EndShapeLabel.setText("End Shape");
		EndShapeLabel.setEnabled(false);

		EndShapeComboBox.setModel(new DefaultComboBoxModel(new String[] { "A-A", "A-B", "A-C", "B-B", "B-C", "C-C" }));
		EndShapeComboBox.setEnabled(false);

		jLabel13.setText("Edge Color");
		jLabel13.setEnabled(false);

		Icon jB8Icon = new ImageIcon("resources/ColorBlue.png");
		jButton8.setIcon(jB8Icon);
		jButton8.setEnabled(false);
		jButton8.setMargin(new java.awt.Insets(2, 5, 2, 5));

		jButton9.setLabel("Save Changes");
		
		*/

		javax.swing.GroupLayout EditPanelLayout = new GroupLayout(EditPanel);
		EditPanel.setLayout(EditPanelLayout);
		/*EditPanelLayout.setHorizontalGroup(
				EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(EditPanelLayout.createSequentialGroup()
						.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(LabelSubtitleLabel)
								.addComponent(NodeSubtitleLabel)
								.addComponent(EdgeSubtitleLabel))
								.addGap(0, 0, Short.MAX_VALUE))
								.addGroup(EditPanelLayout.createSequentialGroup()
										.addContainerGap()
										.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jSeparator2, GroupLayout.Alignment.TRAILING)
												.addComponent(EditTitleLabel, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(LabelTextField)
												.addComponent(LabelFontComboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(EditPanelLayout.createSequentialGroup()
														.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(EditPanelLayout.createSequentialGroup()
																		.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(NodeShapeLabel)
																				.addComponent(LabelColorLabel))
																				.addGap(26, 26, 26)
																				.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(LabelColorBtn)
																						.addComponent(NodeShapeComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
																						.addGroup(EditPanelLayout.createSequentialGroup()
																								.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(LabelTextLabel)
																										.addComponent(LabelFontLabel)
																										.addComponent(BorderColorLabel)
																										.addComponent(FillColorLabel))
																										.addGap(24, 24, 24)
																										.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(FillColorBtn)
																												.addComponent(BorderColorBtn)))
																												.addGroup(EditPanelLayout.createSequentialGroup()
																														.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																																.addComponent(EdgeDesignLabel)
																																.addComponent(EndShapeLabel)
																																.addComponent(jLabel13))
																																.addGap(25, 25, 25)
																																.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																																		.addComponent(jButton8)
																																		.addComponent(EndShapeComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
																																		.addComponent(EdgeDesignComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
																																		.addGap(0, 0, Short.MAX_VALUE))
																																		.addComponent(jSeparator1)
																																		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditPanelLayout.createSequentialGroup()
																																				.addGap(0, 0, Short.MAX_VALUE)
																																				.addComponent(jButton9)))
																																				.addContainerGap())
				);
		EditPanelLayout.setVerticalGroup(
				EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(EditPanelLayout.createSequentialGroup()
						.addComponent(EditTitleLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(LabelSubtitleLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(LabelTextLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(LabelTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(LabelFontLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(LabelFontComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(LabelColorLabel)
								.addComponent(LabelColorBtn))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
								.addGap(3, 3, 3)
								.addComponent(NodeSubtitleLabel)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(NodeShapeLabel)
										.addComponent(NodeShapeComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(BorderColorLabel)
												.addComponent(BorderColorBtn))
												.addGap(18, 18, 18)
												.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(FillColorLabel)
														.addComponent(FillColorBtn))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
														.addGap(11, 11, 11)
														.addComponent(EdgeSubtitleLabel)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(EdgeDesignLabel)
																.addComponent(EdgeDesignComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
																.addGap(18, 18, 18)
																.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(EndShapeLabel)
																		.addComponent(EndShapeComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
																		.addGap(18, 18, 18)
																		.addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(jLabel13)
																				.addComponent(jButton8))
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																				.addComponent(jButton9))
				);*/

		sidePanelScrollPane.setViewportView(EditPanel);

		javax.swing.GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(sidePanelScrollPane, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
								.addComponent(filler1, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
								.addGap(0, 0, Short.MAX_VALUE))
				);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(sidePanelScrollPane, GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(filler1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0))
				);

		FileDropdownMenu.setText("File");

		NewGraphMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
		NewGraphMenuItem.setText("New Graph...");
		NewGraphMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				NewGraphMenuItemActionPerformed(evt);
			}
		});
		FileDropdownMenu.add(NewGraphMenuItem);

		OpenMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
		OpenMenuItem.setText("Open...");
		OpenMenuItem.addActionListener(new java.awt.event.ActionListener(){
			public void actionPerformed(java.awt.event.ActionEvent evt){
				OpenMenuItemActionPerformed(evt);
			}
		});
		FileDropdownMenu.add(OpenMenuItem);

		SaveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
		SaveMenuItem.setText("Save");
		FileDropdownMenu.add(SaveMenuItem);

		SaveAsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
		SaveAsMenuItem.setText("Save As...");
		SaveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SaveAsMenuItemActionPerformed(evt);
			}
		});
		FileDropdownMenu.add(SaveAsMenuItem);

		PrintMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
		PrintMenuItem.setText("Print...");
		FileDropdownMenu.add(PrintMenuItem);

		PrintPreviewMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
		PrintPreviewMenuItem.setText("Print Preview");
		FileDropdownMenu.add(PrintPreviewMenuItem);

		CloseGraphMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
		CloseGraphMenuItem.setText("Close Graph");
		CloseGraphMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CloseGraphMenuItemActionPerformed(evt);
			}
		});
		FileDropdownMenu.add(CloseGraphMenuItem);

		ExitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
		ExitMenuItem.setText("Exit");
		ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ExitMenuItemActionPerformed(evt);
			}
		});
		FileDropdownMenu.add(ExitMenuItem);

		MainWindowMenuBar.add(FileDropdownMenu);

		EditDropdownMenu.setText("Edit");

		SelectAllMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
		SelectAllMenuItem.setText("Select All");
		SelectAllMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SelectAllMenuItemActionPerformed(evt);
			}
		});
		EditDropdownMenu.add(SelectAllMenuItem);

		SelectAllNodesMenuItem.setText("Select All Nodes");
		EditDropdownMenu.add(SelectAllNodesMenuItem);

		SelectAllEdgesMenuItem.setText("Select All Edges");
		EditDropdownMenu.add(SelectAllEdgesMenuItem);

		DeselectMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
		DeselectMenuItem.setText("Deselect");
		EditDropdownMenu.add(DeselectMenuItem);

		MainWindowMenuBar.add(EditDropdownMenu);

		ViewDropdownMenu.setText("View");

		CloseTabMenuItem.setText("Close Tab");
		CloseTabMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CloseTabMenuItemActionPerformed(evt);
			}
		});
		ViewDropdownMenu.add(CloseTabMenuItem);

		CloseAllOtherTabsMenuItem.setText("Close All Other Tabs");
		CloseAllOtherTabsMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt){
				CloseAllOtherTabsMenuItemActionPerformed(evt);
			}
		});
		ViewDropdownMenu.add(CloseAllOtherTabsMenuItem);

		OpenAdvancedCodeViewMenuItem.setText("Open Advanced Code View");
		ViewDropdownMenu.add(OpenAdvancedCodeViewMenuItem);

		MainWindowMenuBar.add(ViewDropdownMenu);

		ToolsDropdownMenu.setText("Tools");

		AutoLabelNodesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
		AutoLabelNodesMenuItem.setSelected(true);
		AutoLabelNodesMenuItem.setText("Auto-Label Nodes");
		AutoLabelNodesMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AutoLabelNodesMenuItemActionPerformed(evt);
			}
		});
		ToolsDropdownMenu.add(AutoLabelNodesMenuItem);

		AutoLabelEdgesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
		AutoLabelEdgesMenuItem.setText("Auto-Label Edges");
		ToolsDropdownMenu.add(AutoLabelEdgesMenuItem);

		AutoConnectNodesMenuItem.setText("Auto-Connect Nodes");
		AutoConnectNodesMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AutoConnectNodesMenuItemActionPerformed(evt);
			}
		});
		ToolsDropdownMenu.add(AutoConnectNodesMenuItem);

		ChangeBgColorMenuItem.setText("Change Background Color");
		ToolsDropdownMenu.add(ChangeBgColorMenuItem);

		MainWindowMenuBar.add(ToolsDropdownMenu);

		HelpDropdownMenu.setText("Help");

		ViewUserGuideMenuItem.setText("View User Guide");
		HelpDropdownMenu.add(ViewUserGuideMenuItem);

		AboutAutographMenuItem.setText("About Autograph...");
		HelpDropdownMenu.add(AboutAutographMenuItem);

		MainWindowMenuBar.add(HelpDropdownMenu);

		setJMenuBar(MainWindowMenuBar);

		javax.swing.GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(MainWindowTabbedPane, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addComponent(MainWindowToolBar, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(MainWindowToolBar, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(MainWindowTabbedPane, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
								.addContainerGap())
				);

		pack();
	}// </editor-fold>

	private void AutoLabelNodesTogActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void AutoLabelEdgesTogActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * Opens a new tab on the main window with an empty graph.
	 * @param evt
	 */
	private void NewGraphMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		//first get a unique title for the new tab
		String newTitle = "New Graph";
		if(MainWindowTabbedPane.getTabCount() > 0){
			Boolean uniqueTitle = false;
			int currentNum = 1;
			while(!uniqueTitle){
				//loop through each tab and check the titles.
				for(int i = 0; i < MainWindowTabbedPane.getTabCount(); i++){
					GraphPanel panel = (GraphPanel)(((JScrollPane)MainWindowTabbedPane.getComponentAt(i)).getViewport().getView());
					//check the current tab has the same name as the new title we are creating
					if(panel.mGetGraph().mGetTitle().compareTo(newTitle) == 0){
						//if it does reset newTitle to be of the form "New Graph[1]"
						newTitle = "New Graph[" + currentNum + "]";
						currentNum++;
						break;
					}
					if(i == MainWindowTabbedPane.getTabCount() - 1){
						//if we get here then we have gone through the whole list and not found
						//a duplicate title, so we will break out of the while loop.
						uniqueTitle = true;
					}
				}
			}
		}
		
		//KMW Note: We are simply creating a new blank tab right now. We do not need to worry
		//          about drawing any graphs in this function.
		Graph newGraph = new Graph(newTitle);
		//GraphHelper.mImportGraphFromXML("Graph.xml");
		JScrollPane newPane = new JScrollPane();
		GraphPanel newGraphPanel = new GraphPanel(newGraph);
		newPane.setBorder(null);

		newGraphPanel.setBackground(new java.awt.Color(255, 255, 255));
		newGraphPanel.setPreferredSize(new java.awt.Dimension(600, 600));

		newPane.setViewportView(newGraphPanel);

		javax.swing.GroupLayout newGraphPanelLayout = new GroupLayout(newGraphPanel);
		newGraphPanel.setLayout(newGraphPanelLayout);
		newGraphPanelLayout.setHorizontalGroup(
				newGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 912, Short.MAX_VALUE)
				);
		newGraphPanelLayout.setVerticalGroup(
				newGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 476, Short.MAX_VALUE)
				);
		MainWindowTabbedPane.addTab(newTitle, newPane);

	}

	private void SelectAllMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		//MainWindowTabbedPane.selectedTab.graph.vSelectedItems.mSelectAllNodes();
	}

	private void CloseTabMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		int selectedTab = MainWindowTabbedPane.getSelectedIndex();
		MainWindowTabbedPane.remove(selectedTab);
	}

	private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		this.exit();
	}

	private void CloseGraphMenuItemActionPerformed(java.awt.event.ActionEvent evt){
		int selectedTab = MainWindowTabbedPane.getSelectedIndex();
		MainWindowTabbedPane.remove(selectedTab);
	}

	private void CloseAllOtherTabsMenuItemActionPerformed(java.awt.event.ActionEvent evt){
		int selectedTab = MainWindowTabbedPane.getSelectedIndex();
		int initialCount = MainWindowTabbedPane.getTabCount();
		//we are removing from the end of the list because the count and index of the last item
		//will constantly shift if we remove from the front of the list, giving inaccurate results.
		for(int i = initialCount -1; i >= 0; i--){
			if(i != selectedTab){
				MainWindowTabbedPane.remove(i);
			}
		}
	}

	private void SaveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt){
		FilePickerDialog saveDialog = new FilePickerDialog(this, true);
		saveDialog.mOpenSaveDialog(MainWindowTabbedPane);
	}

	/**
	 * Open the file picker dialog.
	 * @param evt
	 */
	private void OpenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		FilePickerDialog dialog = new FilePickerDialog(this, true);
		dialog.mOpenFilePickerDialog(MainWindowTabbedPane);
	}

	private void AutoLabelNodesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void AutoConnectNodesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void AddNodeBtnActionPerformed(java.awt.event.MouseEvent evt) {
		// Bring up the Add Node panel
		sidePanelScrollPane.setViewportView(addNodePanel);
	}
	
	private void AddEdgeBtnActionPerformed(java.awt.event.MouseEvent evt) {
		// Bring up the Add Node panel
		sidePanelScrollPane.setViewportView(addEdgePanel);
	}

	public static JTabbedPane getMainWindowPane() {
		return MainWindowTabbedPane;
	}
	
	public static void resetSidePane() {
		sidePanelScrollPane.setViewportView(EditPanel);
	}
	
	// Variables declaration - do not modify
	private JMenuItem AboutAutographMenuItem;
	private JButton AddEdgeBtn;
	private JButton AddNodeBtn;
	private JCheckBoxMenuItem AutoConnectNodesMenuItem;
	private JToggleButton AutoConnectNodesTog;
	private JCheckBoxMenuItem AutoLabelEdgesMenuItem;
	private JToggleButton AutoLabelEdgesTog;
	private JCheckBoxMenuItem AutoLabelNodesMenuItem;
	private JToggleButton AutoLabelNodesTog;
	//private JButton BorderColorBtn;
	//private JLabel BorderColorLabel;
	private JMenuItem ChangeBgColorMenuItem;
	private JMenuItem CloseAllOtherTabsMenuItem;
	private JMenuItem CloseGraphMenuItem;
	private JMenuItem CloseTabMenuItem;
	private JMenuItem DeselectMenuItem;
	//private JComboBox EdgeDesignComboBox;
	//private JLabel EdgeDesignLabel;
	//private JLabel EdgeSubtitleLabel;
	private JMenu EditDropdownMenu;
	private static JPanel EditPanel;
	//private JLabel EditTitleLabel;
	//private JComboBox EndShapeComboBox;
	//private JLabel EndShapeLabel;
	private JMenuItem ExitMenuItem;
	private JMenu FileDropdownMenu;
	//private JButton FillColorBtn;
	//private JLabel FillColorLabel;
	private JMenu HelpDropdownMenu;
	//private JButton LabelColorBtn;
	//private JLabel LabelColorLabel;
	//private JComboBox LabelFontComboBox;
	//private JLabel LabelFontLabel;
	//private JLabel LabelSubtitleLabel;
	//private JTextField LabelTextField;
	//private JLabel LabelTextLabel;
	private JMenuBar MainWindowMenuBar;
	protected static JTabbedPane MainWindowTabbedPane;
	private JToolBar MainWindowToolBar;
	private JMenuItem NewGraphMenuItem;
	//private JComboBox NodeShapeComboBox;
	//private JLabel NodeShapeLabel;
	//private JLabel NodeSubtitleLabel;
	private JMenuItem OpenAdvancedCodeViewMenuItem;
	private JMenuItem OpenMenuItem;
	private JMenuItem PrintMenuItem;
	private JMenuItem PrintPreviewMenuItem;
	private JMenuItem SaveAsMenuItem;
	private JMenuItem SaveMenuItem;
	private JMenuItem SelectAllEdgesMenuItem;
	private JMenuItem SelectAllMenuItem;
	private JMenuItem SelectAllNodesMenuItem;
	//private JScrollPane TabAreaScrollPane;
	private JMenu ToolsDropdownMenu;
	private JMenu ViewDropdownMenu;
	private JMenuItem ViewUserGuideMenuItem;
	private Box.Filler filler1;
	private Box.Filler filler2;
	private Box.Filler filler3;
	private Box.Filler filler4;
	private Box.Filler filler5;
	//private JButton jButton8;
	//private JButton jButton9;
	//private JLabel jLabel13;
	private JPanel jPanel2;
	public GraphPanel GraphTabSubPane;
	//private JScrollPane jScrollPane2;
	private JScrollPane GraphTabPane;
	private static JScrollPane sidePanelScrollPane;
	//private JSeparator jSeparator1;
	//private JSeparator jSeparator2;

	// The side panels
	protected AddNodePanel addNodePanel;
	protected AddEdgePanel addEdgePanel;
	protected EditNodePanel editNodePanel;
	protected EditEdgePanel editEdgePanel;
	protected EditNodeEdgePanel editNodeEdgePanel;

}


